branch-defaults:
    devops-setup:
        environment: test
        group_suffix: null
    master:
        environment: Trackcovid-env
deploy:
    artifact: dist/cues-api.zip
global:
    application_name: isotope-api
    branch: null
    default_ec2_keyname: aws-ssh
    default_platform: Node.js
    default_region: us-east-1
    include_git_submodules: true
    instance_profile: null
    platform_name: null
    platform_version: null
    profile: null
    repository: null
    sc: git
    workspace_type: Application
    container_commands:
    01_fix_static_cors:
        command: '/tmp/fix_static_cors.sh'
files:
    '/tmp/fix_static_cors.sh':
        mode: '000755'
        owner: root
        group: root
        content: |
            #!/bin/bash
            pushd $(/opt/elasticbeanstalk/bin/get-config container -k config_staging_dir)
            echo "Adding CORS Config"
            PROXY_CONF="#etc#nginx#conf.d#00_elastic_beanstalk_proxy.conf"
            grep static_cors.config $PROXY_CONF || sed -i '/location \/static {/a \ \ \ \ include /etc/nginx/conf.d/static_cors.config;' $PROXY_CONF
    '/etc/nginx/conf.d/static_cors.config':
        mode: '000644'
        owner: root
        group: root
        content: |
            #
            # Wide-open CORS config for nginx
            #
            if ($request_method = 'OPTIONS') {
              add_header 'Access-Control-Allow-Origin' '*';
              #
              # Om nom nom cookies
              #
              add_header 'Access-Control-Allow-Credentials' 'true';
              add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
              #
              # Custom headers and headers various browsers *should* be OK with but aren't
              #
              add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
              #
              # Tell client that this pre-flight info is valid for 20 days
              #
              add_header 'Access-Control-Max-Age' 1728000;
              add_header 'Content-Type' 'text/plain charset=UTF-8';
              add_header 'Content-Length' 0;
              return 204;
            }
            if ($request_method = 'POST') {
              add_header 'Access-Control-Allow-Origin' '*';
              add_header 'Access-Control-Allow-Credentials' 'true';
              add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
              add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
            }
            if ($request_method = 'GET') {
              add_header 'Access-Control-Allow-Origin' '*';
              add_header 'Access-Control-Allow-Credentials' 'true';
              add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
              add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
            }
